### ISSUE TITLE
TR_ env vars fail to modify settings.conf

### ISSUE THREAD

**Issue by laur89** [dperson/transmission#17]
Running this image from unraid server, and providing TR_ environment variables don't appear to be editing the config file. These are the params provided:

`-p 9091:9091 -v /mnt/user/downloads/complete:/mnt/user/downloads/complete -v /mnt/user/downloads/incomplete:/mnt/user/downloads/incomplete -e USERID=1000 -e GROUPID=100 -e TRUSER=admin -e TRPASSWD=admin -e TR_DOWNLOAD_DIR=/mnt/user/downloads/complete -e TR_INCOMPLETE_DIR=/mnt/user/downloads/incomplete`

The container log provided by unraid shows these sed errors in the beginning:

> sed: -e expression #1, char 30: unknown option to `s'
> sed: -e expression #1, char 28: unknown option to `s'

Actual conf is still left unchanged:
```
    "download-dir": "/var/lib/transmission-daemon/downloads", 
    "download-limit": 100, 
    "download-limit-enabled": 0, 
    "download-queue-enabled": true, 
    "download-queue-size": 5, 
    "encryption": 1, 
    "idle-seeding-limit": 30, 
    "idle-seeding-limit-enabled": false, 
    "incomplete-dir": "/var/lib/transmission-daemon/incomplete", 
```
Could it be due to fact unraid is using ancient docker ver?

> Docker version 1.10.3, build ceb0ccd-unsupported

**Comment by laur89** [comment]
Crap, somehow missed the requirement of docker 1.3. Closed.

**Comment by laur89** [comment]
Misread my docker ver. It's obviously new enough. Reopened.

**Comment by dperson** [comment]
Please, pull the latest version and try again. I think it should be fixed now. Thanks for reporting the issue.

**Comment by MartinFournier** [comment]
This seems to be still happening using the latest docker image.
```sh
#docker rm -f transmission-test && \
docker pull dperson/transmission:latest && \
docker run --name transmission-test \
   -it -d -e "TR_RATIO_LIMIT=11" dperson/transmission:latest && \
sleep 10s && \
docker exec -it transmission-test \
  sh -c 'cat /var/lib/transmission-daemon/info/settings.json | grep ratio && printenv | grep RATIO' && \
docker logs transmission-test
```
```
settings.json --> "ratio-limit": 2,
printenv --> TR_RATIO_LIMIT=11
```

I'm also getting a permission denied with /dev/stdout in the container's log
``` Couldn't open "/dev/stdout": Permission denied ```
Using Docker 1.11.1-beta13.1 on OSX

**Comment by dperson** [comment]
@MartinFournier the issue you were seeing was different. I had the script checking to see if the setting was already in the file, and when it looked for `ratio-limit` it found the `ratio-limit-enabled` setting and took the wrong logic branch in the code. I think that the `/dev/stdout` error should be fixed as well.

@laur89 I found another issue that might have stopped the particular settings that you wanted from working. If you were still having problems they should be fixed now.

**Comment by MartinFournier** [comment]
@dperson Thank you!
Probably a mistake but you added the launch flag  ```--allowed \\*``` which sets the rpc-whitelist to any ip regardless of configured setting (https://github.com/dperson/transmission/blob/master/transmission.sh#L110)

**Comment by dperson** [comment]
That's actually been there from the beginning (it just got moved around). I don't bother to assign an IP to each container manually (or want to). I use the user/password for access control to the web interface instead of an IP white list.
